/**
 * Land bundled example results. Responsibilities differ from boltz-landing:
 *
 * - boltz-landing handles newly completed jobs through short-lived presigned URLs.
 * - this module handles reusable static assets stored under public/.
 *
 * Multiple candidates occupy separate viewports so users can compare them side by side.
 *
 * This module owns layout and delivery rather than using loadMultipleInModeler, whose consumer uses
 * a crystallographic CIF parser. Boltz outputs mmCIF and would otherwise create empty viewports.
 */

import { useModelerBridge, type PendingMultiFile } from '../host/modelerBridge'
import { parseLegacyPdb } from '../lib/biomolecule/pdb'
import { mmcifToPdbText } from '../lib/biomolecule/mmcif'
import { getActiveViewportStoreApi } from '../orchestration/ViewportContext'
import { useViewportManager, type GridLayout } from '../orchestration/viewportManager'

/** Bundled candidate matching the manifest generated by fetch-boltz-examples.mts. */
export interface StoredExampleCandidate {
  /** Stable scientific ranking score prepared when the example is generated. */
  score: number
  /** Public path to the complete predicted structure used by the viewer. */
  structure: string
}

/** One bundled example case. */
export interface StoredExample {
  id: string
  candidates: readonly StoredExampleCandidate[]
}

/**
 * Map structure count to the same grid rules used by modelerBridge.loadMultipleInModeler.
 */
function layoutForCount(count: number): GridLayout {
  if (count <= 1) return '1x1'
  if (count === 2) return '1x2'
  if (count <= 4) return '2x2'
  if (count <= 6) return '2x3'
  if (count <= 8) return '2x4'
  if (count <= 12) return '3x4'
  return '4x4'
}

/** Stable ranking score prepared with the same policy as boltz-landing.designScore. */
export function exampleScore(candidate: StoredExampleCandidate): number {
  return Number.isFinite(candidate.score) ? candidate.score : 0
}

async function fetchText(path: string, signal?: AbortSignal): Promise<string> {
  const response = await fetch(`${import.meta.env.BASE_URL}${path}`, { signal })
  if (!response.ok) throw new Error(`取 ${path} 失败: HTTP ${response.status}`)
  return response.text()
}

/**
 * Spread example candidates across viewports and return the number successfully loaded.
 *
 * The default limit fills a 2x4 grid without shrinking larger candidate sets into a 4x4 layout.
 */
export async function landExampleCandidates(
  example: StoredExample,
  options?: { signal?: AbortSignal; limit?: number },
): Promise<{ landed: number; skipped: number }> {
  const limit = options?.limit ?? 8
  const ranked = [...example.candidates]
    .sort((a, b) => exampleScore(b) - exampleScore(a))
    .slice(0, limit)

  const files: PendingMultiFile[] = []
  let skipped = 0

  for (const [index, candidate] of ranked.entries()) {
    if (!candidate.structure) {
      skipped += 1
      continue
    }
    try {
      const mmcif = await fetchText(candidate.structure, options?.signal)
      const score = exampleScore(candidate)
      // Include rank and score in each viewport title for direct comparison.
      const label = `${index + 1}${score > 0 ? ` · ${score.toFixed(2)}` : ''}`
      files.push({ name: label, content: mmcif, format: 'cif' })
    } catch {
      // One missing candidate must not abort the batch.
      skipped += 1
    }
  }

  if (files.length === 0) return { landed: 0, skipped }

  // Parse through mmcifToPdbText -> parseLegacyPdb -> loadBiomolecule and declare pLDDT semantics;
  // loadMultipleInModeler uses a crystallographic CIF parser that silently rejects these mmCIF files.
  const manager = useViewportManager.getState()
  manager.setLayout(layoutForCount(files.length))

  // Wait one microtask for setLayout to create viewport slots.
  await new Promise((resolve) => queueMicrotask(() => resolve(null)))

  const latest = useViewportManager.getState()
  const viewportIds = Object.keys(latest.viewports).sort()
  let landed = 0

  for (const [index, file] of files.entries()) {
    const viewportId = viewportIds[index]
    if (!viewportId) break
    const storeHook = latest.getViewportStore(viewportId)
    if (!storeHook) continue

    const pdbText = mmcifToPdbText(file.content, { title: file.name })
    const structure = parseLegacyPdb(pdbText, {
      id: `${example.id}-${index}`,
      bFactorSemantics: 'plddt',
    })
    const state = storeHook.getState()
    state.loadBiomolecule(structure)
    state.resetStructureGroupsToBase()
    latest.setStructureName(viewportId, file.name)
    landed += 1
  }

  // Clear grid slots beyond the candidate count so they cannot retain structures from a previous case.
  for (const viewportId of viewportIds.slice(landed)) {
    const storeHook = latest.getViewportStore(viewportId)
    if (!storeHook) continue
    // clearStructure removes both bioStructure and its atom mirror; clearBiomolecule leaves stale points.
    storeHook.getState().clearStructure()
    latest.setStructureName(viewportId, '')
  }

  if (viewportIds.length > 0) latest.setActive(viewportIds[0]!)
  useModelerBridge.getState().switchToModeler?.()

  return { landed, skipped }
}

/**
 * Land a single prediction example by replacing the document through the live-result path.
 *
 * Pass bFactorSemantics='plddt' explicitly because Boltz stores pLDDT in B-factor columns while
 * automatic detection recognizes AlphaFold names only.
 */
export async function landExampleComplex(
  example: StoredExample,
  options?: { signal?: AbortSignal },
): Promise<{ atomCount: number; chainCount: number }> {
  const first = example.candidates[0]
  if (!first) throw new Error(`示例 ${example.id} 没有可展示的结构产物`)

  const mmcif = await fetchText(first.structure, options?.signal)
  const pdbText = mmcifToPdbText(mmcif, { title: example.id })
  const structure = parseLegacyPdb(pdbText, { id: example.id, bFactorSemantics: 'plddt' })

  const store = getActiveViewportStoreApi().getState()
  store.loadBiomolecule(structure)
  store.resetStructureGroupsToBase()

  return { atomCount: structure.atoms.length, chainCount: structure.chains.length }
}
