import { describe, expect, it, vi } from 'vitest'

import { CubParser } from '../CubParser'
import { MoldenParser } from '../MoldenParser'

const moldenWithHeader = (header: string) => `[Molden Format]
generated by test
[Atoms] ${header}
H 1 1 1.0 0.0 0.0
[GTO]
1 0
s 1 1.00
1.0 1.0

[MO]
Sym= A1
Ene= -0.5
Spin= Alpha
Occup= 2.0
1 1.0
`

describe('MoldenParser atom units', () => {
  it.each([
    { header: '(AU)', expectedX: 0.529177210903 },
    { header: '(Angs)', expectedX: 1 },
  ])('parses the common [Atoms] $header header', ({ header, expectedX }) => {
    const parsed = new MoldenParser(moldenWithHeader(header)).parse()

    expect(parsed.atoms).toHaveLength(1)
    expect(parsed.atoms[0]).toMatchObject({ symbol: 'H', index: 1, atomicNumber: 1 })
    expect(parsed.atoms[0]!.x).toBeCloseTo(expectedX, 12)
    expect(parsed.basis).toHaveLength(1)
    expect(parsed.gtos).toHaveLength(1)
    expect(parsed.orbitals).toHaveLength(1)
    expect(parsed.orbitals[0]).toMatchObject({ symmetry: 'A1', energy: -0.5, spin: 'Alpha', occupation: 2 })
  })
})

describe('volumetric parser logging', () => {
  it('does not write per-file parsing progress to the production console', () => {
    const log = vi.spyOn(console, 'log').mockImplementation(() => undefined)
    try {
      new MoldenParser(moldenWithHeader('(AU)')).parse()
      new CubParser().parse(`cube title
cube comment
1 0.0 0.0 0.0
1 1.0 0.0 0.0
1 0.0 1.0 0.0
1 0.0 0.0 1.0
1 0.0 0.0 0.0 0.0
0.5
`)
      expect(log).not.toHaveBeenCalled()
    } finally {
      log.mockRestore()
    }
  })
})
