import { describe, expect, it } from 'vitest'

import { createCrystalStore } from '../../../orchestration/crystalStore'
import { importUnifiedStructureText } from '../../../services/unified-file-import'
import type { CubData } from '../CubParser'
import {
  ELECTRON_DENSITY_CUB_SURFACE_DEFAULTS,
  ORBITAL_CUB_SURFACE_DEFAULTS,
  cubSurfaceRenderDefaults,
  isElectronDensityCub,
} from '../state'

function evidence(title: string, comment = ''): Pick<CubData, 'title' | 'comment'> {
  return { title, comment }
}

function cube(title: string): string {
  return [
    title,
    'content-aware defaults fixture',
    '1 0 0 0',
    '2 1 0 0',
    '2 0 1 0',
    '2 0 0 1',
    '1 0 0 0 0',
    '0.001 0.002 0.003 0.004 0.005 0.006 0.007 0.008',
  ].join('\n')
}

const molden = `[Molden Format]
generated by defaults test
[Atoms] (Angs)
H 1 1 0.0 0.0 0.0
[GTO]
1 0
s 1 1.00
1.0 1.0

[MO]
Sym= A1
Ene= -0.5
Spin= Alpha
Occup= 2.0
1 1.0
`

describe('Cube surface import defaults', () => {
  it('recognizes total electron and charge densities from contents or filename', () => {
    expect(isElectronDensityCub(evidence('Electron density in real space'), 'field.cube')).toBe(true)
    expect(isElectronDensityCub(evidence('scalar field'), 'electron-density.cube')).toBe(true)
    expect(isElectronDensityCub(evidence('VASP total charge density'), 'CHGCAR.cube')).toBe(true)
    expect(cubSurfaceRenderDefaults(evidence('Electron density in real space'))).toBe(
      ELECTRON_DENSITY_CUB_SURFACE_DEFAULTS,
    )
  })

  it('does not apply total-density defaults to signed density fields or orbitals', () => {
    const misleadingSpinHeader = evidence('Electron density in real space')
    expect(isElectronDensityCub(misleadingSpinHeader, 'spin-density.cube')).toBe(false)
    expect(isElectronDensityCub(evidence('VASP magnetization density'), 'magnetization-density.cube')).toBe(false)
    expect(isElectronDensityCub(evidence('Orbital value in real space'), 'density-study/orbital-homo.cube')).toBe(false)
    expect(isElectronDensityCub(evidence('Molecular electrostatic potential'), 'density.cube')).toBe(false)
    expect(cubSurfaceRenderDefaults(evidence('Orbital value in real space'), 'orbital-homo.cube')).toBe(
      ORBITAL_CUB_SURFACE_DEFAULTS,
    )
    expect(cubSurfaceRenderDefaults(evidence('Molecular electrostatic potential'), 'esp.cube')).toBe(
      ORBITAL_CUB_SURFACE_DEFAULTS,
    )
  })

  it('applies density defaults through the unified import path and restores orbital defaults on the next Cube', async () => {
    const store = createCrystalStore()
    store.getState().setMolecularOrbitalIsoValue(0.14)
    store.getState().setMolecularOrbitalOpacity(0.2)
    store.getState().setMolecularOrbitalResolution(18)

    const densityResult = await importUnifiedStructureText(
      'electron-density.cube',
      cube('Electron density in real space'),
      store,
    )
    expect(densityResult.success).toBe(true)
    expect(store.getState().molecularOrbital).toMatchObject({
      sourceName: 'electron-density.cube',
      isoValue: 0.002,
      opacity: 0.86,
      resolution: 60,
    })

    const orbitalResult = await importUnifiedStructureText(
      'orbital-lumo.cube',
      cube('Orbital value in real space'),
      store,
    )
    expect(orbitalResult.success).toBe(true)
    expect(store.getState().molecularOrbital).toMatchObject({
      sourceName: 'orbital-lumo.cube',
      isoValue: 0.03,
      opacity: 0.62,
      resolution: 34,
    })
  })

  it('restores orbital defaults when a Molden wavefunction follows a density Cube', async () => {
    const store = createCrystalStore()
    await importUnifiedStructureText(
      'electron-density.cube',
      cube('Electron density in real space'),
      store,
    )

    const moldenResult = await importUnifiedStructureText('wavefunction.molden', molden, store)

    expect(moldenResult.success).toBe(true)
    expect(store.getState().molecularOrbital).toMatchObject({
      sourceType: 'molden',
      sourceName: 'wavefunction.molden',
      isoValue: 0.03,
      opacity: 0.62,
      resolution: 34,
    })
  })
})
