export interface RegionAssignment {
  /** Per-atom region id, with the same length as the atom array. */
  regionOf: Uint32Array
  /** Unique region ids in ascending order. */
  regionIds: number[]
}

/** Preserve the grain ids generated by the polycrystal builder as render regions. */
export function regionsFromGrainId(grainId: Uint32Array): RegionAssignment {
  const ids = new Set<number>()
  for (let index = 0; index < grainId.length; index++) ids.add(grainId[index])
  return { regionOf: grainId, regionIds: [...ids].sort((left, right) => left - right) }
}
