/**
 * Void / cavity / specific-surface-area analysis — pure frontend.
 *
 * Builds a signed-distance scalar field f(x) = min_i( d_i(x) − (R_vdw_i + r_probe) )
 * over the cell (PBC-aware minimum image when periodic): f ≥ 0 ⇔ a probe sphere
 * of radius r_probe centred at x clears every atom's vdW surface. The f = 0
 * iso-surface is the solvent-accessible surface (SAS) traced by the probe centre.
 *
 *   - void volume  = ∫ [f ≥ 0]            (probe-accessible free volume)
 *   - accessible surface area = area of the f = 0 marching-cubes mesh
 *   - specific surface area   = area / total mass  (m²/g)
 *
 * The mesh is generated by the existing OptimizedMarchingCubes and coloured
 * per-vertex by the nearest-atom-centre distance (a pore-openness map).
 */

import { OptimizedMarchingCubes } from "../../molecular-orbitals/OptimizedMarchingCubes"
import { getElement } from "../../crystal/elements"

/** Bondi (+ common-extension) van-der-Waals radii (Å). Fallback 1.70. */
const VDW: Record<string, number> = {
  H: 1.2, He: 1.4, Li: 1.82, Be: 1.53, B: 1.92, C: 1.7, N: 1.55, O: 1.52, F: 1.47, Ne: 1.54,
  Na: 2.27, Mg: 1.73, Al: 1.84, Si: 2.1, P: 1.8, S: 1.8, Cl: 1.75, Ar: 1.88,
  K: 2.75, Ca: 2.31, Sc: 2.11, Ti: 2.0, V: 2.0, Cr: 2.0, Mn: 2.0, Fe: 2.0, Co: 2.0, Ni: 1.97,
  Cu: 1.96, Zn: 2.01, Ga: 1.87, Ge: 2.11, As: 1.85, Se: 1.9, Br: 1.85, Kr: 2.02,
  Rb: 3.03, Sr: 2.49, Y: 2.1, Zr: 2.07, Nb: 2.05, Mo: 2.1, Ru: 2.05, Rh: 2.0, Pd: 1.63, Ag: 1.72,
  Cd: 1.58, In: 1.93, Sn: 2.17, Sb: 2.06, Te: 2.06, I: 1.98, Xe: 2.16,
  Cs: 3.43, Ba: 2.68, La: 2.4, Hf: 2.1, Ta: 2.05, W: 2.1, Re: 2.05, Os: 2.0, Ir: 2.0, Pt: 1.75, Au: 1.66,
  Hg: 1.55, Tl: 1.96, Pb: 2.02, Bi: 2.07,
}
function vdwRadius(el: string): number {
  return VDW[el] ?? 1.7
}

type Vec3 = [number, number, number]

export interface VoidAnalysisInput {
  atoms: { element: string; cartesian: Vec3 }[]
  latticeVectors: { a: Vec3; b: Vec3; c: Vec3 } | null
  periodic: boolean
  probeRadius: number
  resolution: number // grid points per axis (mesh + volume)
}

export interface VoidAnalysisResult {
  voidVolumeAng3: number
  voidFractionPct: number
  accessibleSurfaceAreaAng2: number
  specificSurfaceArea_m2g: number
  cellVolumeAng3: number
  probeRadius: number
  resolution: number
  mesh: { vertices: Float32Array; normals: Float32Array; faces: Uint32Array }
  /** Per-vertex scalar (nearest-atom-centre distance, Å) for colour mapping. */
  vertexScalar: Float32Array
  scalarRange: [number, number]
}

function det3(m: number[][]): number {
  return (
    m[0][0] * (m[1][1] * m[2][2] - m[1][2] * m[2][1]) -
    m[0][1] * (m[1][0] * m[2][2] - m[1][2] * m[2][0]) +
    m[0][2] * (m[1][0] * m[2][1] - m[1][1] * m[2][0])
  )
}
function inv3(m: number[][]): number[][] {
  const d = det3(m)
  if (Math.abs(d) < 1e-12) return [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
  const id = 1 / d
  return [
    [(m[1][1] * m[2][2] - m[1][2] * m[2][1]) * id, (m[0][2] * m[2][1] - m[0][1] * m[2][2]) * id, (m[0][1] * m[1][2] - m[0][2] * m[1][1]) * id],
    [(m[1][2] * m[2][0] - m[1][0] * m[2][2]) * id, (m[0][0] * m[2][2] - m[0][2] * m[2][0]) * id, (m[0][2] * m[1][0] - m[0][0] * m[1][2]) * id],
    [(m[1][0] * m[2][1] - m[1][1] * m[2][0]) * id, (m[0][1] * m[2][0] - m[0][0] * m[2][1]) * id, (m[0][0] * m[1][1] - m[0][1] * m[1][0]) * id],
  ]
}

export function analyzeVoid(input: VoidAnalysisInput): VoidAnalysisResult {
  const { atoms, latticeVectors, periodic, probeRadius, resolution } = input
  const n = atoms.length
  const px = new Float64Array(n), py = new Float64Array(n), pz = new Float64Array(n)
  const reach = new Float64Array(n) // R_vdw + probe
  let mass = 0
  for (let i = 0; i < n; i++) {
    const c = atoms[i].cartesian
    px[i] = c[0]; py[i] = c[1]; pz[i] = c[2]
    reach[i] = vdwRadius(atoms[i].element) + probeRadius
    mass += getElement(atoms[i].element).mass || 0
  }

  const usePbc = periodic && !!latticeVectors
  // lattice matrix rows a,b,c (cart = frac · L); Linv for fractional coords
  const L = usePbc ? [latticeVectors!.a, latticeVectors!.b, latticeVectors!.c].map((r) => [...r]) : [[1, 0, 0], [0, 1, 0], [0, 0, 1]]
  const Linv = inv3(L)
  const cellVol = usePbc ? Math.abs(det3(L)) : 0

  // bounds: AABB of the cell (periodic) or atom bbox + padding (molecule)
  let min: Vec3, max: Vec3
  if (usePbc) {
    min = [Infinity, Infinity, Infinity]; max = [-Infinity, -Infinity, -Infinity]
    for (let i = 0; i < 8; i++) {
      const fa = i & 1, fb = (i >> 1) & 1, fc = (i >> 2) & 1
      const x = fa * L[0][0] + fb * L[1][0] + fc * L[2][0]
      const y = fa * L[0][1] + fb * L[1][1] + fc * L[2][1]
      const z = fa * L[0][2] + fb * L[1][2] + fc * L[2][2]
      min = [Math.min(min[0], x), Math.min(min[1], y), Math.min(min[2], z)]
      max = [Math.max(max[0], x), Math.max(max[1], y), Math.max(max[2], z)]
    }
  } else {
    const pad = probeRadius + 2.5
    min = [Infinity, Infinity, Infinity]; max = [-Infinity, -Infinity, -Infinity]
    for (let i = 0; i < n; i++) {
      min = [Math.min(min[0], px[i]), Math.min(min[1], py[i]), Math.min(min[2], pz[i])]
      max = [Math.max(max[0], px[i]), Math.max(max[1], py[i]), Math.max(max[2], pz[i])]
    }
    min = [min[0] - pad, min[1] - pad, min[2] - pad]
    max = [max[0] + pad, max[1] + pad, max[2] + pad]
  }
  const aabbVol = (max[0] - min[0]) * (max[1] - min[1]) * (max[2] - min[2])

  const res = Math.max(8, Math.min(120, Math.floor(resolution)))
  const np1 = res + 1
  const step: Vec3 = [(max[0] - min[0]) / res, (max[1] - min[1]) / res, (max[2] - min[2]) / res]

  // signed distance to the NEAREST atom's vdW+probe surface, PBC min-image
  const fieldAt = (x: number, y: number, z: number): number => {
    let best = Infinity
    if (usePbc) {
      // fractional of the query point
      const fx = x * Linv[0][0] + y * Linv[1][0] + z * Linv[2][0]
      const fy = x * Linv[0][1] + y * Linv[1][1] + z * Linv[2][1]
      const fz = x * Linv[0][2] + y * Linv[1][2] + z * Linv[2][2]
      for (let i = 0; i < n; i++) {
        const afx = px[i] * Linv[0][0] + py[i] * Linv[1][0] + pz[i] * Linv[2][0]
        const afy = px[i] * Linv[0][1] + py[i] * Linv[1][1] + pz[i] * Linv[2][1]
        const afz = px[i] * Linv[0][2] + py[i] * Linv[1][2] + pz[i] * Linv[2][2]
        let dfx = fx - afx, dfy = fy - afy, dfz = fz - afz
        dfx -= Math.round(dfx); dfy -= Math.round(dfy); dfz -= Math.round(dfz)
        const dx = dfx * L[0][0] + dfy * L[1][0] + dfz * L[2][0]
        const dy = dfx * L[0][1] + dfy * L[1][1] + dfz * L[2][1]
        const dz = dfx * L[0][2] + dfy * L[1][2] + dfz * L[2][2]
        const d = Math.sqrt(dx * dx + dy * dy + dz * dz) - reach[i]
        if (d < best) best = d
      }
    } else {
      for (let i = 0; i < n; i++) {
        const dx = x - px[i], dy = y - py[i], dz = z - pz[i]
        const d = Math.sqrt(dx * dx + dy * dy + dz * dz) - reach[i]
        if (d < best) best = d
      }
    }
    return best
  }

  // precompute the field grid once (index = i + j*np1 + k*np1²) + integrate volume
  const grid = new Float32Array(np1 * np1 * np1)
  let voidInCell = 0, totalInCell = 0
  for (let k = 0; k <= res; k++) {
    const z = min[2] + k * step[2]
    for (let j = 0; j <= res; j++) {
      const y = min[1] + j * step[1]
      for (let i = 0; i <= res; i++) {
        const x = min[0] + i * step[0]
        const f = fieldAt(x, y, z)
        grid[i + j * np1 + k * np1 * np1] = f
        // in-cell test for the volume integral (periodic: fractional ∈ [0,1))
        let inCell = true
        if (usePbc) {
          const ffx = x * Linv[0][0] + y * Linv[1][0] + z * Linv[2][0]
          const ffy = x * Linv[0][1] + y * Linv[1][1] + z * Linv[2][1]
          const ffz = x * Linv[0][2] + y * Linv[1][2] + z * Linv[2][2]
          inCell = ffx >= 0 && ffx < 1 && ffy >= 0 && ffy < 1 && ffz >= 0 && ffz < 1
        }
        if (inCell) {
          totalInCell++
          if (f >= 0) voidInCell++
        }
      }
    }
  }
  const voidFraction = totalInCell > 0 ? voidInCell / totalInCell : 0
  const refVol = usePbc ? cellVol : aabbVol
  const voidVolumeAng3 = voidFraction * refVol

  // marching cubes on the precomputed grid at iso = 0 → SAS mesh (world coords)
  const mc = new OptimizedMarchingCubes()
  const mesh = mc.generateFromGrid(grid, { min, max }, np1, 0, { smoothIterations: 1, smoothFactor: 0.5, sharedVertices: true })

  // surface area = Σ triangle areas
  let area = 0
  const V = mesh.vertices, F = mesh.faces
  for (let t = 0; t + 2 < F.length; t += 3) {
    const a = F[t] * 3, b = F[t + 1] * 3, c = F[t + 2] * 3
    const ux = V[b] - V[a], uy = V[b + 1] - V[a + 1], uz = V[b + 2] - V[a + 2]
    const vx = V[c] - V[a], vy = V[c + 1] - V[a + 1], vz = V[c + 2] - V[a + 2]
    const cx = uy * vz - uz * vy, cy = uz * vx - ux * vz, cz = ux * vy - uy * vx
    area += 0.5 * Math.sqrt(cx * cx + cy * cy + cz * cz)
  }

  // Per-vertex colour scalar = SECOND-nearest wall distance (channel openness).
  // The nearest-atom-surface distance ≈ probe everywhere on the SAS (that is the
  // surface's definition), so it is nearly uniform and useless for colouring; the
  // distance to the SECOND-nearest atom surface instead reflects how wide the
  // channel/pore is at each point (large in open cavities, small in tight necks).
  const vdwOnly = new Float64Array(n)
  for (let i = 0; i < n; i++) vdwOnly[i] = reach[i] - probeRadius
  const secondNearestSurface = (x: number, y: number, z: number): number => {
    let m1 = Infinity, m2 = Infinity
    if (usePbc) {
      const fx = x * Linv[0][0] + y * Linv[1][0] + z * Linv[2][0]
      const fy = x * Linv[0][1] + y * Linv[1][1] + z * Linv[2][1]
      const fz = x * Linv[0][2] + y * Linv[1][2] + z * Linv[2][2]
      for (let i = 0; i < n; i++) {
        const afx = px[i] * Linv[0][0] + py[i] * Linv[1][0] + pz[i] * Linv[2][0]
        const afy = px[i] * Linv[0][1] + py[i] * Linv[1][1] + pz[i] * Linv[2][1]
        const afz = px[i] * Linv[0][2] + py[i] * Linv[1][2] + pz[i] * Linv[2][2]
        let dfx = fx - afx, dfy = fy - afy, dfz = fz - afz
        dfx -= Math.round(dfx); dfy -= Math.round(dfy); dfz -= Math.round(dfz)
        const dx = dfx * L[0][0] + dfy * L[1][0] + dfz * L[2][0]
        const dy = dfx * L[0][1] + dfy * L[1][1] + dfz * L[2][1]
        const dz = dfx * L[0][2] + dfy * L[1][2] + dfz * L[2][2]
        const sd = Math.sqrt(dx * dx + dy * dy + dz * dz) - vdwOnly[i]
        if (sd < m1) { m2 = m1; m1 = sd } else if (sd < m2) m2 = sd
      }
    } else {
      for (let i = 0; i < n; i++) {
        const dx = x - px[i], dy = y - py[i], dz = z - pz[i]
        const sd = Math.sqrt(dx * dx + dy * dy + dz * dz) - vdwOnly[i]
        if (sd < m1) { m2 = m1; m1 = sd } else if (sd < m2) m2 = sd
      }
    }
    return Number.isFinite(m2) ? m2 : m1
  }
  const nv = V.length / 3
  const vertexScalar = new Float32Array(nv)
  let smin = Infinity, smax = -Infinity
  for (let i = 0; i < nv; i++) {
    const g = secondNearestSurface(V[i * 3], V[i * 3 + 1], V[i * 3 + 2])
    vertexScalar[i] = g
    if (g < smin) smin = g
    if (g > smax) smax = g
  }
  if (!Number.isFinite(smin)) { smin = 0; smax = 1 }

  const massG = mass * 1.66053906660e-24
  const areaM2 = area * 1e-20
  const ssa = massG > 0 ? areaM2 / massG : 0

  return {
    voidVolumeAng3,
    voidFractionPct: voidFraction * 100,
    accessibleSurfaceAreaAng2: area,
    specificSurfaceArea_m2g: ssa,
    cellVolumeAng3: refVol,
    probeRadius,
    resolution: res,
    mesh,
    vertexScalar,
    scalarRange: [smin, smax],
  }
}
