// Periodic Table Element Data
// Contains atomic radii (pm), colors, and covalent radii for bond calculations

export interface Element {
  symbol: string
  name: string
  atomicNumber: number
  atomicMass: number
  color: string // Hex color for visualization
  radius: number // Van der Waals radius in Angstroms
  covalentRadius: number // Covalent radius in Angstroms for bond detection
}

export const ELEMENTS: Record<string, Element> = {
  H: {
    symbol: 'H',
    name: 'Hydrogen',
    atomicNumber: 1,
    atomicMass: 1.008,
    color: '#FFFFFF',
    radius: 1.2,
    covalentRadius: 0.31,
  },
  He: {
    symbol: 'He',
    name: 'Helium',
    atomicNumber: 2,
    atomicMass: 4.003,
    color: '#D9FFFF',
    radius: 1.4,
    covalentRadius: 0.28,
  },
  Li: {
    symbol: 'Li',
    name: 'Lithium',
    atomicNumber: 3,
    atomicMass: 6.941,
    color: '#CC80FF',
    radius: 1.82,
    covalentRadius: 1.28,
  },
  Be: {
    symbol: 'Be',
    name: 'Beryllium',
    atomicNumber: 4,
    atomicMass: 9.012,
    color: '#C2FF00',
    radius: 1.53,
    covalentRadius: 0.96,
  },
  B: {
    symbol: 'B',
    name: 'Boron',
    atomicNumber: 5,
    atomicMass: 10.81,
    color: '#FFB5B5',
    radius: 1.92,
    covalentRadius: 0.84,
  },
  C: {
    symbol: 'C',
    name: 'Carbon',
    atomicNumber: 6,
    atomicMass: 12.011,
    color: '#505050',
    radius: 1.7,
    covalentRadius: 0.76,
  },
  N: {
    symbol: 'N',
    name: 'Nitrogen',
    atomicNumber: 7,
    atomicMass: 14.007,
    color: '#3050F8',
    radius: 1.55,
    covalentRadius: 0.71,
  },
  O: {
    symbol: 'O',
    name: 'Oxygen',
    atomicNumber: 8,
    atomicMass: 15.999,
    color: '#FF0D0D',
    radius: 1.52,
    covalentRadius: 0.66,
  },
  F: {
    symbol: 'F',
    name: 'Fluorine',
    atomicNumber: 9,
    atomicMass: 18.998,
    color: '#90E050',
    radius: 1.47,
    covalentRadius: 0.57,
  },
  Ne: {
    symbol: 'Ne',
    name: 'Neon',
    atomicNumber: 10,
    atomicMass: 20.18,
    color: '#B3E3F5',
    radius: 1.54,
    covalentRadius: 0.58,
  },
  Na: {
    symbol: 'Na',
    name: 'Sodium',
    atomicNumber: 11,
    atomicMass: 22.99,
    color: '#AB5CF2',
    radius: 2.27,
    covalentRadius: 1.66,
  },
  Mg: {
    symbol: 'Mg',
    name: 'Magnesium',
    atomicNumber: 12,
    atomicMass: 24.305,
    color: '#8AFF00',
    radius: 1.73,
    covalentRadius: 1.41,
  },
  Al: {
    symbol: 'Al',
    name: 'Aluminum',
    atomicNumber: 13,
    atomicMass: 26.982,
    color: '#BFA6A6',
    radius: 1.84,
    covalentRadius: 1.21,
  },
  Si: {
    symbol: 'Si',
    name: 'Silicon',
    atomicNumber: 14,
    atomicMass: 28.086,
    color: '#F0C8A0',
    radius: 2.1,
    covalentRadius: 1.11,
  },
  P: {
    symbol: 'P',
    name: 'Phosphorus',
    atomicNumber: 15,
    atomicMass: 30.974,
    color: '#FF8000',
    radius: 1.8,
    covalentRadius: 1.07,
  },
  S: {
    symbol: 'S',
    name: 'Sulfur',
    atomicNumber: 16,
    atomicMass: 32.065,
    color: '#FFFF30',
    radius: 1.8,
    covalentRadius: 1.05,
  },
  Cl: {
    symbol: 'Cl',
    name: 'Chlorine',
    atomicNumber: 17,
    atomicMass: 35.453,
    color: '#1FF01F',
    radius: 1.75,
    covalentRadius: 1.02,
  },
  Ar: {
    symbol: 'Ar',
    name: 'Argon',
    atomicNumber: 18,
    atomicMass: 39.948,
    color: '#80D1E3',
    radius: 1.88,
    covalentRadius: 1.06,
  },
  K: {
    symbol: 'K',
    name: 'Potassium',
    atomicNumber: 19,
    atomicMass: 39.098,
    color: '#8F40D4',
    radius: 2.75,
    covalentRadius: 2.03,
  },
  Ca: {
    symbol: 'Ca',
    name: 'Calcium',
    atomicNumber: 20,
    atomicMass: 40.078,
    color: '#3DFF00',
    radius: 2.31,
    covalentRadius: 1.76,
  },
  Ti: {
    symbol: 'Ti',
    name: 'Titanium',
    atomicNumber: 22,
    atomicMass: 47.867,
    color: '#BFC2C7',
    radius: 2.11,
    covalentRadius: 1.6,
  },
  V: {
    symbol: 'V',
    name: 'Vanadium',
    atomicNumber: 23,
    atomicMass: 50.942,
    color: '#A6A6AB',
    radius: 2.07,
    covalentRadius: 1.53,
  },
  Cr: {
    symbol: 'Cr',
    name: 'Chromium',
    atomicNumber: 24,
    atomicMass: 51.996,
    color: '#8A99C7',
    radius: 2.06,
    covalentRadius: 1.39,
  },
  Mn: {
    symbol: 'Mn',
    name: 'Manganese',
    atomicNumber: 25,
    atomicMass: 54.938,
    color: '#9C7AC7',
    radius: 2.05,
    covalentRadius: 1.39,
  },
  Fe: {
    symbol: 'Fe',
    name: 'Iron',
    atomicNumber: 26,
    atomicMass: 55.845,
    color: '#E06633',
    radius: 2.04,
    covalentRadius: 1.32,
  },
  Co: {
    symbol: 'Co',
    name: 'Cobalt',
    atomicNumber: 27,
    atomicMass: 58.933,
    color: '#F090A0',
    radius: 2.0,
    covalentRadius: 1.26,
  },
  Ni: {
    symbol: 'Ni',
    name: 'Nickel',
    atomicNumber: 28,
    atomicMass: 58.693,
    color: '#50D050',
    radius: 1.97,
    covalentRadius: 1.24,
  },
  Cu: {
    symbol: 'Cu',
    name: 'Copper',
    atomicNumber: 29,
    atomicMass: 63.546,
    color: '#C88033',
    radius: 1.96,
    covalentRadius: 1.32,
  },
  Zn: {
    symbol: 'Zn',
    name: 'Zinc',
    atomicNumber: 30,
    atomicMass: 65.38,
    color: '#7D80B0',
    radius: 2.01,
    covalentRadius: 1.22,
  },
  Ga: {
    symbol: 'Ga',
    name: 'Gallium',
    atomicNumber: 31,
    atomicMass: 69.723,
    color: '#C28F8F',
    radius: 1.87,
    covalentRadius: 1.22,
  },
  Ge: {
    symbol: 'Ge',
    name: 'Germanium',
    atomicNumber: 32,
    atomicMass: 72.64,
    color: '#668F8F',
    radius: 2.11,
    covalentRadius: 1.2,
  },
  As: {
    symbol: 'As',
    name: 'Arsenic',
    atomicNumber: 33,
    atomicMass: 74.922,
    color: '#BD80E3',
    radius: 1.85,
    covalentRadius: 1.19,
  },
  Se: {
    symbol: 'Se',
    name: 'Selenium',
    atomicNumber: 34,
    atomicMass: 78.96,
    color: '#FFA100',
    radius: 1.9,
    covalentRadius: 1.2,
  },
  Br: {
    symbol: 'Br',
    name: 'Bromine',
    atomicNumber: 35,
    atomicMass: 79.904,
    color: '#A62929',
    radius: 1.85,
    covalentRadius: 1.2,
  },
  Kr: {
    symbol: 'Kr',
    name: 'Krypton',
    atomicNumber: 36,
    atomicMass: 83.798,
    color: '#5CB8D1',
    radius: 2.02,
    covalentRadius: 1.16,
  },
  Ag: {
    symbol: 'Ag',
    name: 'Silver',
    atomicNumber: 47,
    atomicMass: 107.868,
    color: '#C0C0C0',
    radius: 2.11,
    covalentRadius: 1.45,
  },
  Au: {
    symbol: 'Au',
    name: 'Gold',
    atomicNumber: 79,
    atomicMass: 196.967,
    color: '#FFD123',
    radius: 2.14,
    covalentRadius: 1.36,
  },
  Pt: {
    symbol: 'Pt',
    name: 'Platinum',
    atomicNumber: 78,
    atomicMass: 195.084,
    color: '#D0D0E0',
    radius: 2.1,
    covalentRadius: 1.36,
  },
}

// Get element by symbol, with fallback
export function getElement(symbol: string): Element {
  return (
    ELEMENTS[symbol] || {
      symbol,
      name: 'Unknown',
      atomicNumber: 0,
      atomicMass: 0,
      color: '#FF00FF',
      radius: 1.5,
      covalentRadius: 1.0,
    }
  )
}

// All element symbols for the periodic table selector
export const ELEMENT_SYMBOLS = Object.keys(ELEMENTS)
